# Generated by Django 3.1.1 on 2020-11-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('choice1', models.BooleanField(default=False)),
                ('choice2', models.BooleanField(default=False)),
                ('choice3', models.BooleanField(default=False)),
                ('choice4', models.BooleanField(default=False)),
                ('choice5', models.BooleanField(default=False)),
                ('choice6', models.BooleanField(default=False)),
                ('choice7', models.BooleanField(default=False)),
                ('choice8', models.BooleanField(default=False)),
                ('choice9', models.BooleanField(default=False)),
                ('choice10', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('choice1', models.BooleanField(default=False)),
                ('choice2', models.BooleanField(default=False)),
                ('choice3', models.BooleanField(default=False)),
                ('choice4', models.BooleanField(default=False)),
                ('choice5', models.BooleanField(default=False)),
                ('choice6', models.BooleanField(default=False)),
                ('choice7', models.BooleanField(default=False)),
                ('choice8', models.BooleanField(default=False)),
                ('choice9', models.BooleanField(default=False)),
                ('choice10', models.BooleanField(default=False)),
            ],
        ),
    ]
