# Generated by Django 3.1.1 on 2020-11-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='friends',
            field=models.IntegerField(default=0),
        ),
    ]
