# Generated by Django 3.1.3 on 2020-11-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_master_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='current',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='current',
            field=models.IntegerField(default=1),
        ),
    ]
