# Generated by Django 3.1.1 on 2020-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201120_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.AddField(
            model_name='player',
            name='from_master',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
